# Generated by Django 5.2.17 on 2026-10-01 23:06

import apps.pizarras.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('archivado_en', models.DateTimeField(blank=True, help_text='Vacío = activo. Archivado = solo lectura para todos sus miembros.', null=True, verbose_name='archivado en')),
                ('creado_por', models.ForeignKey(help_text='Quién lo creó. El dueño actual está en sus miembros (puede haber cambiado).', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MiembroProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('dueno', 'Dueño'), ('miembro', 'Miembro')], default='miembro', max_length=10, verbose_name='rol')),
                ('puede_crear', models.BooleanField(default=True, verbose_name='puede crear tarjetas')),
                ('puede_editar', models.BooleanField(default=True, verbose_name='puede editar tarjetas')),
                ('puede_cambiar_estatus', models.BooleanField(default=True, verbose_name='puede cambiar estatus')),
                ('puede_eliminar', models.BooleanField(default=False, verbose_name='puede eliminar tarjetas')),
                ('puede_gestionar_tipos', models.BooleanField(default=False, verbose_name='puede gestionar tipos')),
                ('unido_en', models.DateTimeField(auto_now_add=True, verbose_name='unido en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='pizarras.proyecto', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'miembro',
                'verbose_name_plural': 'miembros',
                'ordering': ['rol', 'usuario__email'],
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'usuario'), name='miembro_unico'), models.UniqueConstraint(condition=models.Q(('rol', 'dueno')), fields=('proyecto',), name='proyecto_un_solo_dueno'), models.CheckConstraint(condition=models.Q(('rol__in', ['dueno', 'miembro'])), name='miembro_rol_valido')],
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('token', models.CharField(default=apps.pizarras.models.generar_token, editable=False, max_length=64, unique=True, verbose_name='token')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10, verbose_name='estado')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('enviada_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='último envío')),
                ('veces_enviada', models.PositiveSmallIntegerField(default=1, verbose_name='veces enviada')),
                ('respondida_en', models.DateTimeField(blank=True, null=True, verbose_name='respondida en')),
                ('aceptada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_aceptadas', to=settings.AUTH_USER_MODEL, verbose_name='aceptada por')),
                ('invitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='invitada por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='pizarras.proyecto', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'invitación',
                'verbose_name_plural': 'invitaciones',
                'ordering': ['-creada_en'],
                'constraints': [models.UniqueConstraint(models.F('proyecto'), django.db.models.functions.text.Lower('correo'), condition=models.Q(('estado', 'pendiente')), name='invitacion_pendiente_unica')],
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-f]{6}$', 'El color debe tener el formato #rrggbb (p. ej. #3b5bdb).')], verbose_name='color')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='pizarras.proyecto', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'tipo de tarjeta',
                'verbose_name_plural': 'tipos de tarjeta',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(models.F('proyecto'), django.db.models.functions.text.Lower('nombre'), name='tipo_nombre_unico_en_proyecto'), models.CheckConstraint(condition=models.Q(('color__regex', '^#[0-9a-f]{6}$')), name='tipo_color_valido')],
            },
        ),
    ]
