# Generated by Django 5.2.17 on 2026-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizarras', '0005_tipotarjeta_a_tipoactividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoactividad',
            options={'ordering': ['nombre'], 'verbose_name': 'tipo de actividad', 'verbose_name_plural': 'tipos de actividad'},
        ),
        migrations.AlterField(
            model_name='miembropizarra',
            name='puede_crear',
            field=models.BooleanField(default=True, verbose_name='puede crear actividades'),
        ),
        migrations.AlterField(
            model_name='miembropizarra',
            name='puede_editar',
            field=models.BooleanField(default=True, verbose_name='puede editar actividades'),
        ),
        migrations.AlterField(
            model_name='miembropizarra',
            name='puede_eliminar',
            field=models.BooleanField(default=False, verbose_name='puede eliminar actividades'),
        ),
        migrations.AlterField(
            model_name='miembropizarra',
            name='puede_mover',
            field=models.BooleanField(default=True, verbose_name='puede mover actividades'),
        ),
    ]
