# Generated by Django 5.2.17 on 2026-10-06 20:36

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizarras', '0006_nombres_de_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('pizarra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to='pizarras.pizarra', verbose_name='pizarra')),
            ],
            options={
                'verbose_name': 'solicitante',
                'verbose_name_plural': 'solicitantes',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(models.F('pizarra'), django.db.models.functions.text.Lower('nombre'), name='solicitante_nombre_unico_en_pizarra')],
            },
        ),
    ]
