# Generated by Django 5.2.17 on 2026-10-01 23:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('tarjetas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_anterior', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], max_length=20, verbose_name='estatus anterior')),
                ('estatus_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], max_length=20, verbose_name='estatus nuevo')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'cambio de estatus',
                'verbose_name_plural': 'historial de estatus',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='proyectos.proyecto', verbose_name='proyecto'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='tarjetas', to='proyectos.tipotarjeta', verbose_name='tipos'),
        ),
        migrations.AddIndex(
            model_name='tarjeta',
            index=models.Index(fields=['proyecto', 'estatus'], name='tarjeta_proyecto_estatus'),
        ),
        migrations.AddField(
            model_name='cambioestatus',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estatus', to='tarjetas.tarjeta', verbose_name='tarjeta'),
        ),
        migrations.AddField(
            model_name='cambioestatus',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Vacío si la cuenta se borró: el cambio se conserva («Usuario eliminado»).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estatus', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddIndex(
            model_name='cambioestatus',
            index=models.Index(fields=['tarjeta', '-fecha'], name='cambio_tarjeta_fecha'),
        ),
    ]
