# Generated by Django 5.2.17 on 2026-10-01 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('tarjetas', '0005_proyecto_obligatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='prioridad'),
        ),
        migrations.AddConstraint(
            model_name='tarjeta',
            constraint=models.CheckConstraint(condition=models.Q(('prioridad__in', ['baja', 'media', 'alta', 'urgente'])), name='tarjeta_prioridad_valida'),
        ),
    ]
