# Generated by Django 5.2.17 on 2026-10-02 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def separar_apellidos_y_verificar(apps, schema_editor):
    """
    `apellidos` se parte en la primera palabra y el resto («López Ramírez» → «López», «Ramírez»).
    Falla con apellidos compuestos («De la Torre»); cada quien lo corrige en su perfil.

    Las cuentas que ya existían quedan verificadas: entraron sin código y no se les debe cerrar
    la puerta por una regla nueva.
    """
    Usuario = apps.get_model("usuarios", "Usuario")
    for u in Usuario.objects.all():
        primero, _, resto = (u.apellidos or "").strip().partition(" ")
        u.primer_apellido = primero[:100]
        u.segundo_apellido = resto.strip()[:100]
        u.correo_verificado_en = u.creado_en
        u.save(update_fields=["primer_apellido", "segundo_apellido", "correo_verificado_en"])


def juntar_apellidos(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    for u in Usuario.objects.all():
        u.apellidos = f"{u.primer_apellido} {u.segundo_apellido}".strip()[:150]
        u.save(update_fields=["apellidos"])


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_verificado_en',
            field=models.DateTimeField(blank=True, help_text='Vacío: la cuenta aún no confirma su correo y no puede entrar a la app.', null=True, verbose_name='correo verificado en'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='primer apellido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='segundo apellido'),
        ),
        migrations.RunPython(separar_apellidos_y_verificar, juntar_apellidos),
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.CreateModel(
            name='CodigoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposito', models.CharField(choices=[('verificar', 'Verificar correo'), ('recuperar', 'Recuperar contraseña')], max_length=10, verbose_name='propósito')),
                ('codigo_hash', models.CharField(max_length=64, verbose_name='código (HMAC)')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='intentos fallidos')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'código por correo',
                'verbose_name_plural': 'códigos por correo',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'proposito', '-creado_en'], name='usuarios_co_usuario_a9456f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('proposito__in', ['verificar', 'recuperar'])), name='codigo_correo_proposito_valido')],
            },
        ),
    ]
