# Generated by Django 5.2.17 on 2026-10-01 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='asignados',
            field=models.ManyToManyField(blank=True, related_name='tarjetas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='asignados'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AddConstraint(
            model_name='tarjeta',
            constraint=models.CheckConstraint(condition=models.Q(('estatus__in', ['pendiente', 'en_curso', 'finalizada'])), name='tarjeta_estatus_valido'),
        ),
    ]
