# Generated by Django 5.2.17 on 2026-10-01 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizarras', '0001_initial'),
        ('actividades', '0004_tarjetas_existentes_a_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='pizarras.proyecto', verbose_name='proyecto'),
        ),
    ]
