# Generated by Django 5.2.17 on 2026-10-06 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_notas_del_historial'),
        ('pizarras', '0006_nombres_de_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['posicion', 'id'], 'verbose_name': 'actividad', 'verbose_name_plural': 'actividades'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='asignados',
            field=models.ManyToManyField(blank=True, related_name='actividades_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='asignados'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='actividades', to='pizarras.lista', verbose_name='lista'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='pizarra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='pizarras.pizarra', verbose_name='pizarra'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='actividades', to='pizarras.tipoactividad', verbose_name='tipos'),
        ),
        migrations.AlterField(
            model_name='elementochecklist',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='actividades.actividad', verbose_name='actividad'),
        ),
        migrations.AlterField(
            model_name='elementochecklist',
            name='actividad_creada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elemento_origen', to='actividades.actividad', verbose_name='actividad creada'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='actividades.actividad', verbose_name='actividad'),
        ),
    ]
