# Generated by Django 5.2.17 on 2026-10-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_fecha_solicitud'),
        ('pizarras', '0006_nombres_de_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='lista_al_completar',
            field=models.ForeignKey(blank=True, help_text='Vacía: completar la checklist no la mueve.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pizarras.lista', verbose_name='al completar la checklist, mover a'),
        ),
        migrations.AlterField(
            model_name='elementochecklist',
            name='texto',
            field=models.CharField(max_length=400, verbose_name='texto'),
        ),
    ]
