# Generated by Django 5.2.17 on 2026-10-06 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0016_checklist_400_y_al_completar'),
        ('pizarras', '0007_solicitantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='solicitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por (miembro)'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='solicitante_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='pizarras.solicitante', verbose_name='solicitada por (externo)'),
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.CheckConstraint(condition=models.Q(('solicitada_por__isnull', True), ('solicitante_externo__isnull', True), _connector='OR'), name='actividad_un_solicitante'),
        ),
    ]
