# Generated by Django 5.2.17 on 2026-10-06 23:07

import apps.actividades.almacen
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0017_solicitantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('archivo', models.FileField(max_length=200, storage=apps.actividades.almacen.AlmacenAdjuntos(), upload_to=apps.actividades.almacen.ruta_adjunto, verbose_name='archivo')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('tamano', models.PositiveBigIntegerField(verbose_name='tamaño (bytes)')),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='actividades.actividad', verbose_name='actividad')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'adjunto',
                'verbose_name_plural': 'adjuntos',
                'ordering': ['creado_en', 'id'],
            },
        ),
    ]
